update axum to 0.7.1
ChainCashLabs/chaincash-rs pull request #35
Opened 2023-11-27 21:21 UTC by zackbalbin

2023-11-27 22:01 UTC, ross-weir requested changes
Awesome, thanks a lot!

Just a few small things before merging

2023-11-27 22:01 UTC, ross-weir commented on crates/chaincash_server/src/api.rs
> +            .unwrap()
Could we please keep this how it was previously, swap import of `hyper::StatusCode` to `axum::http::StatusCode` should do the trick

2023-11-27 22:01 UTC, ross-weir commented on crates/chaincash_server/src/app.rs
> +        axum::serve::serve(listener,
lets do `listener.try_into()?` with the parameter directly here instead of using a var & `from_std`

2023-11-27 22:01 UTC, ross-weir commented on crates/chaincash_server/src/app.rs
> -            .with_graceful_shutdown(Self::shutdown())
Could you please remove `Self::shutdown` method as we're no longer using it

2023-11-28 00:48 UTC, zackbalbin commented
sounds good! made the changes

2023-11-28 01:43 UTC, ross-weir requested changes

2023-11-28 01:43 UTC, ross-weir commented on crates/chaincash_server/src/api.rs
> +        let body = Body::from(json!({
Sorry, I meant when using `axum::http::StatusCode` we can keep the rest of this how it was like:

```rust
//...
        let body = Json(json!({
            "error": {
                "detail": msg,
            }
        }));

        (status_code, body).into_response()
```

2023-11-28 05:25 UTC, ross-weir requested changes
Just one suggestion and we're good to go

2023-11-28 05:25 UTC, ross-weir commented on crates/chaincash_server/src/api.rs
> +        }).to_string());
```suggestion
        }));
```

2023-11-28 05:28 UTC, zackbalbin commented on crates/chaincash_server/src/api.rs
> +        }).to_string());
ah yeah forgot to remove that after switching back to Json from Body

2023-11-28 07:38 UTC, ross-weir approved these changes
Nice one, thank you! :rocket:

2023-11-28 07:38 UTC, merged