Log output to filesystem
ChainCashLabs/chaincash-rs pull request #37
Opened 2023-12-02 12:14 UTC by SethDusek

For #5 

Some questions:
- Is rotating log files daily fine or should I adjust the rotation interval?
- Writing logs to ./chaincash.log.d/chaincash.log*. I was looking for where the standard place to put log files on Linux for user programs is, and there doesn't seem to be one (besides /var/log which requires special privileges to create a log directory). So I assume putting this in the current directory is fine.

2023-12-02 20:32 UTC, ross-weir commented
> Is rotating log files daily fine or should I adjust the rotation interval?

yeah that's fine

> Writing logs to ./chaincash.log.d/chaincash.log*. I was looking for where the standard place to put log files on Linux for user programs is, and there doesn't seem to be one (besides /var/log which requires special privileges to create a log directory). So I assume putting this in the current directory is fine.

Lets add `directories-rs` dependency and put logs in the dirs specified here: https://github.com/dirs-dev/directories-rs/issues/81

2023-12-03 13:22 UTC, sethdusek commented
> Lets add `directories-rs` dependency and put logs in the dirs specified here: [dirs-dev/directories-rs#81](https://github.com/dirs-dev/directories-rs/issues/81)

Done! Also watching the github issue so if (and when) this is built-in to directories-rs I can replace our implementation with that

2023-12-03 19:57 UTC, ross-weir requested changes

2023-12-03 19:57 UTC, ross-weir commented on crates/chaincash_cli/src/main.rs
> +        let mut log_directory = get_log_directory().unwrap_or_default();
Lets use `std::env::current_dir` as fallback default, `PathBuf::default` returns an empty string

2023-12-03 19:58 UTC, ross-weir commented
> > Lets add `directories-rs` dependency and put logs in the dirs specified here: [dirs-dev/directories-rs#81](https://github.com/dirs-dev/directories-rs/issues/81)
> 
> Done! Also watching the github issue so if (and when) this is built-in to directories-rs I can replace our implementation with that

Amazing, thank you!

Just one more small thing and will merge.

Whats your discord/telegram? I'll get kushti to contact you for bounty payment

2023-12-04 09:52 UTC, sethdusek commented
> > > Lets add `directories-rs` dependency and put logs in the dirs specified here: [dirs-dev/directories-rs#81](https://github.com/dirs-dev/directories-rs/issues/81)
> > 
> > 
> > Done! Also watching the github issue so if (and when) this is built-in to directories-rs I can replace our implementation with that
> 
> Amazing, thank you!
> 
> Just one more small thing and will merge.
> 
> Whats your discord/telegram? I'll get kushti to contact you for bounty payment

My Discord username is dusek_. Thanks!

2023-12-04 21:30 UTC, merged

2023-12-06 11:32 UTC, kushti commented
@SethDusek please provide your Ergo address (ordinary or stealth) over Discord (sent you DM there) or email kushti@protonmail.ch